### ISSUE TITLE
Maximum call stack size exceeded...

### ISSUE THREAD

**Issue by RK-Veltec** [dagrejs/dagre#248]
I'm using a tweaked version of this cytoscape.js example (http://www.wineandcheesemap.com/). 
I'm trying to plot a hierarchical tree with 3452 nodes and 3451 edges.

Firstly, I tried using:
- dagre 0.7.4
- cytoscape.js 2.7.12
- cytoscape-dagre 1.6.0
I get the following error:

> Maximum call stack size exceeded
> at .../dagre.js:2368:61
> at arrayReduce (.../dagre.js:6112:31)
> at Function.<anonymous> (.../dagre.js:8124:19)...

I tried then with the newest releases:
- dagre 0.7.4
- cytoscape.js 3.2.15
- cytoscape-dagre 2.2.1

I get the same error as well. 

Just to clarify, line 2368 here starts with this (I beautified the file. Original file says line 1).

```
var min = _.reduce(blockG.outEdges(v), function (min, e) {
  pass2(e.w);
  return Math.min(min, xs[e.w] - blockG.edge(e));
}, Number.POSITIVE_INFINITY);
```

**EDIT:** I tried chopping the root (bringing it down to 3451 nodes and 1369 edges), but the error persists.

**Comment by RK-Veltec** [comment]
It worked using 0.8.2 release. It's quite slow, but it does its job.
